### ISSUE TITLE
Make *.c3IDE file easier to diff for source control

### ISSUE THREAD

**Issue by MikalDev** [armandoalonso/c3IDE#11]
Can the c3IDE file be formatted so it's to diff for source control reviews (e.g. putting (.ce3IDE into github) may be as simple as making file have CR/LF or equivalent instead of one long line of text. Other ideas for easier diff / review of diffs are welcome,

**Comment by armandoalonso** [comment]
I am going to create a new version of the .c3ide file, this version of the file instead of having all the addon data embedded inside, will have relative links to other files, which will hold the addon content. this will allow for better source control integration and diff comparisons with the addon. another change i will make to this type of c3ide,instead of creating a duplicate addon, it will be linked to the existing addon with the same guid. 

this will take me a bit of time to accomplish, since i will not be able to start on it right away. there are a few changes that i need to make first to ensure backwards compatibility with both types of c3ide files.

**Comment by MikalDev** [comment]
Sounds like a good long term plan. I hope c3IDE becomes a big lever for folks making new addons. I will also publish the c3IDE version of whatever I make, so they'll be more examples (I hope others do also, for at least non-paid addons.)

**Comment by armandoalonso** [comment]
this has been deployed, there is an option to export a custom project structure which should work well with version control/diff
