### ISSUE TITLE
Feature to clear server cache

### ISSUE THREAD

**Issue by skymen** [armandoalonso/c3IDE#57]
The server system is cool, but it would be pretty neat to have a way to remove the cache for servers per addon or the whole cache instead of having to go in the appdata folder and delete it manually.

In order to avoid the issue described here in the future: https://github.com/armandoalonso/c3IDE/issues/55#issuecomment-571072967

(Aka a bug was fixed in a newer version, so the content of files change, but when starting the server again, some files don't get updated, and it might still create issues when trying to preview even though the issue has been fixed)

**Comment by armandoalonso** [comment]
there should be no server cache, the server is a static file server which always gives the file under the compile path, on addon compilation (where i merge all the parts of the aces into thier respective file,) the original folder is removed and recreated. there is a compile on save option which automatically compiles the addon for you, if you have the web server running you dont need to make any other changes, if you restart construct (because construct does cache development addons) it should reload the addon, if this is not happening how i described then i will investigate it further

**Comment by armandoalonso** [comment]
i can add a button to clear the folder, should not be needed unless there is a bigger a problem, next time you test and it happens can you copy the log and post it here, see if i might be missing something

**Comment by skymen** [comment]
Never got any issue with this since, so closing.
Will reopen a new issue if I ever get this issue again
